
export type Language = 'en' | 'hi';

export const translations = {
  en: {
    navbar: { ethos: 'Our Ethos', jurisprudence: 'Jurisprudence', resources: 'Resources', securePortal: 'Drafting Portal', login: 'Login', logout: 'Logout' },
    landing: {
      title: 'Sovereign Justice',
      subtitle: 'for Every Citizen',
      description: 'PANU stands for the dignity of the common man. We offer a royal drafting experience for legal petitions—bridging the gap between the court and the marginalized, completely free of the predatory fees of advocates.',
      beginBtn: 'Begin Your Draft',
      feature1Title: 'I. Access',
      feature1Text: 'Secure Google-authenticated access to ensure procedural integrity.',
      feature2Title: 'II. Jurisprudence',
      feature2Text: 'AI trained on centuries of Indian Penal Code and Civil Procedure standards.',
      feature3Title: 'III. Equality',
      feature3Text: 'Eliminating the monetary barrier to justice for those who need it most.'
    },
    verification: {
      title: 'Identify Yourself',
      subtitle: 'Access to justice requires authentic identification.',
      aadhaarLabel: 'Aadhaar Number',
      verifyBtn: 'Verify Identity',
      otpLabel: 'One-Time Passcode',
      confirmBtn: 'Finalize Verification',
      placeholder: '0000 0000 0000',
      loading: 'Authenticating...',
      confirming: 'Confirming...',
      otpHint: 'Sent to your registered mobile number ending in **42'
    },
    drafting: {
      step1: 'Persona', step2: 'Jurisdiction', step3: 'Grievance', step4: 'Drafting',
      petitionerHeader: 'The Petitioner & Respondent',
      petitionerSub: 'Petitioner Details',
      respondentSub: 'Respondent Details',
      jurisdictionHeader: 'Jurisdiction & Case Type',
      causeHeader: 'Statement of Grievance',
      causeOfAction: 'Cause of Action',
      reviewHeader: 'Review & Transcribe',
      reviewSub: 'Your details are verified. Our system will now apply the rigorous standards of Indian Law to generate your petition.',
      generateBtn: 'Generate Legal Draft',
      continueBtn: 'Continue',
      backBtn: 'Back',
      // New field labels
      parentOrSpouseName: 'Parent / Spouse Name',
      firNumber: 'FIR Number & Year',
      policeStation: 'Police Station (P.S.)',
      custodyStatus: 'Status of Accused',
      judicialCustody: 'Judicial Custody',
      anticipatoryBail: 'Anticipatory Bail',
      dateOfCauseOfAction: 'Date of Cause of Action',
      dateOfMarriage: 'Date of Marriage',
      caseSpecificHeader: 'Case-Specific Details',
    },
    loading: {
      title: 'Our Solicitors are Drafting...',
      subtitle: 'Applying Indian Constitutional standards and legal formatting.'
    },
    viewing: {
      watermark: 'PRO BONO',
      downloadBtn: 'Download as PDF',
      resetBtn: 'Draft New Petition',
      footerText: 'Generated by PANU Legal Intelligence Engine'
    },
    pages: {
      ethos: {
        title: 'The PANU Ethos',
        content: 'Justice is not a commodity to be purchased, but a right to be exercised. We believe that the complexity of legal language should not be a barrier to the truth. Our mission is to restore the power of the written word to the hands of the people, guided by the light of the Constitution of India.'
      },
      jurisprudence: {
        title: 'Library of Laws',
        content: 'PANU is founded upon the deep study of Indian Jurisprudence. From the historic verdicts of the Supreme Court to the foundational principles of the IPC and CPC, our engine understands the weight of legal precedent.'
      },
      resources: {
        title: 'Legal Resources',
        content: 'Access the tools necessary for your legal journey. We provide links to NALSA, state legal aid authorities, and simplified guides to the Indian legal system.'
      },
      login: {
        title: 'Registry Access',
        subtitle: 'Enter the Sovereign Vault',
        googleBtn: 'Sign in with Google',
        username: 'Identifier',
        password: 'Passkey',
        submit: 'Enter Portal'
      }
    }
  },
  hi: {
    navbar: { ethos: 'हमारा लोकाचार', jurisprudence: 'न्यायशास्त्र', resources: 'संसाधन', securePortal: 'मसौदा पोर्टल', login: 'लॉगिन', logout: 'लॉगआउट' },
    landing: {
      title: 'संप्रभु न्याय',
      subtitle: 'हर नागरिक के लिए',
      description: 'PANU आम आदमी की गरिमा के लिए खड़ा है। हम कानूनी याचिकाओं के लिए एक शाही मसौदा अनुभव प्रदान करते हैं—अदालत और वंचितों के बीच की दूरी को पाटते हुए, अधिवक्ताओं की शोषणकारी फीस से पूरी तरह मुक्त।',
      beginBtn: 'अपना ड्राफ्ट शुरू करें',
      feature1Title: 'I. पहुँच',
      feature1Text: 'प्रक्रियात्मक अखंडता सुनिश्चित करने के लिए सुरक्षित Google-प्रमाणित पहुँच।',
      feature2Title: 'II. न्यायशास्त्र',
      feature2Text: 'भारतीय दंड संहिता और नागरिक प्रक्रिया मानकों के सदियों के प्रशिक्षण पर आधारित एआई।',
      feature3Title: 'III. समानता',
      feature3Text: 'उन लोगों के लिए न्याय की मौद्रिक बाधा को खत्म करना जिन्हें इसकी सबसे अधिक आवश्यकता है।'
    },
    verification: {
      title: 'अपनी पहचान बताएं',
      subtitle: 'न्याय तक पहुंच के लिए प्रामाणिक पहचान आवश्यक है।',
      aadhaarLabel: 'आधार संख्या',
      verifyBtn: 'पहचान सत्यापित करें',
      otpLabel: 'वन-टाइम पासकोड',
      confirmBtn: 'सत्यापन अंतिम रूप दें',
      placeholder: '0000 0000 0000',
      loading: 'प्रमाणित किया जा रहा है...',
      confirming: 'पुष्टि की जा रही है...',
      otpHint: 'आपके पंजीकृत मोबाइल नंबर पर भेजा गया है'
    },
    drafting: {
      step1: 'व्यक्ति', step2: 'क्षेत्राधिकार', step3: 'शिकायत', step4: 'मसौदा',
      petitionerHeader: 'याचिकाकर्ता और प्रतिवादी',
      petitionerSub: 'याचिकाकर्ता विवरण',
      respondentSub: 'प्रतिवादी विवरण',
      jurisdictionHeader: 'क्षेत्राधिकार और मामला प्रकार',
      causeHeader: 'शिकायत का विवरण',
      causeOfAction: 'कार्रवाई का कारण',
      reviewHeader: 'समीक्षा और प्रतिलेखन',
      reviewSub: 'आपके विवरण सत्यापित हैं। हमारा सिस्टम अब आपकी याचिका तैयार करने के लिए भारतीय कानून के कड़े मानकों को लागू करेगा।',
      generateBtn: 'कानूनी मसौदा तैयार करें',
      continueBtn: 'जारी रखें',
      backBtn: 'पीछे',
      // New field labels
      parentOrSpouseName: 'माता-पिता / पति/पत्नी का नाम',
      firNumber: 'एफआईआर संख्या और वर्ष',
      policeStation: 'थाना (पी.एस.)',
      custodyStatus: 'आरोपी की स्थिति',
      judicialCustody: 'न्यायिक हिरासत',
      anticipatoryBail: 'अग्रिम जमानत',
      dateOfCauseOfAction: 'कार्रवाई के कारण की तिथि',
      dateOfMarriage: 'विवाह की तिथि',
      caseSpecificHeader: 'मामले का विशिष्ट विवरण',
    },
    loading: {
      title: 'हमारे वकील मसौदा तैयार कर रहे हैं...',
      subtitle: 'भारतीय संवैधानिक मानकों और कानूनी प्रारूपों को लागू करना।'
    },
    viewing: {
      watermark: 'जनहित',
      downloadBtn: 'PDF डाउनलोड करें',
      resetBtn: 'नई याचिका का मसौदा तैयार करें',
      footerText: 'PANU कानूनी इंटेलिजेंस इंजन द्वारा निर्मित'
    },
    pages: {
      ethos: {
        title: 'PANU लोकाचार',
        content: 'न्याय खरीदी जाने वाली वस्तु नहीं, बल्कि प्रयोग किया जाने वाला अधिकार है। हमारा मानना है कि कानूनी भाषा की जटिलता सत्य की बाधा नहीं होनी चाहिए। हमारा मिशन भारतीय संविधान के प्रकाश में शब्दों की शक्ति को जनता के हाथों में वापस लाना है।'
      },
      jurisprudence: {
        title: 'कानूनों का पुस्तकालय',
        content: 'PANU भारतीय न्यायशास्त्र के गहरे अध्ययन पर आधारित है। सर्वोच्च न्यायालय के ऐतिहासिक फैसलों से लेकर IPC और CPC के बुनियादी सिद्धांतों तक, हमारा इंजन कानूनी मिसाल के वजन को समझता है।'
      },
      resources: {
        title: 'कानूनी संसाधन',
        content: 'अपनी कानूनी यात्रा के लिए आवश्यक उपकरणों तक पहुंचें। हम NALSA, राज्य कानूनी सहायता अधिकारियों के लिंक और भारतीय कानूनी प्रणाली के सरलीकृत गाइड प्रदान करते हैं।'
      },
      login: {
        title: 'पंजीकरण पहुंच',
        subtitle: 'संप्रभु तिजोरी में प्रवेश करें',
        googleBtn: 'गूगल के साथ साइन इन करें',
        username: 'पहचानकर्ता',
        password: 'पासकी',
        submit: 'पोर्टल में प्रवेश करें'
      }
    }
  }
};
